from __future__ import annotations

from ..models import Migration


ALTER_STATEMENTS = (
    "ALTER TABLE sales ADD COLUMN exchange_id TEXT",
    "ALTER TABLE sales ADD COLUMN warranty_id TEXT",
    "ALTER TABLE sale_items ADD COLUMN exchange_item_id TEXT",
    "ALTER TABLE sale_returns ADD COLUMN return_number INTEGER",
    "ALTER TABLE sale_returns ADD COLUMN customer_id TEXT",
    "ALTER TABLE sale_returns ADD COLUMN status TEXT NOT NULL DEFAULT 'completed'",
    "ALTER TABLE sale_returns ADD COLUMN origin TEXT NOT NULL DEFAULT 'commercial'",
    "ALTER TABLE sale_returns ADD COLUMN gross_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_returns ADD COLUMN discount_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_returns ADD COLUMN net_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_returns ADD COLUMN cost_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_returns ADD COLUMN user_id TEXT",
    "ALTER TABLE sale_returns ADD COLUMN user_name TEXT",
    "ALTER TABLE sale_returns ADD COLUMN idempotency_key TEXT",
    "ALTER TABLE sale_returns ADD COLUMN request_hash TEXT",
    "ALTER TABLE sale_returns ADD COLUMN response_json TEXT",
    "ALTER TABLE sale_returns ADD COLUMN reconciliation_required INTEGER NOT NULL DEFAULT 0",
    "ALTER TABLE sale_returns ADD COLUMN warranty_id TEXT",
    "ALTER TABLE sale_returns ADD COLUMN exchange_id TEXT",
    "ALTER TABLE sale_return_items ADD COLUMN sale_item_id TEXT",
    "ALTER TABLE sale_return_items ADD COLUMN barcode TEXT",
    "ALTER TABLE sale_return_items ADD COLUMN brand TEXT",
    "ALTER TABLE sale_return_items ADD COLUMN size TEXT",
    "ALTER TABLE sale_return_items ADD COLUMN color TEXT",
    "ALTER TABLE sale_return_items ADD COLUMN gross_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_return_items ADD COLUMN allocated_discount REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_return_items ADD COLUMN net_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_return_items ADD COLUMN unit_cost REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_return_items ADD COLUMN cost_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE sale_return_items ADD COLUMN physical_condition TEXT NOT NULL DEFAULT 'resellable'",
    "ALTER TABLE sale_return_items ADD COLUMN restocked INTEGER NOT NULL DEFAULT 1",
    "ALTER TABLE receivables ADD COLUMN return_reduction_total REAL NOT NULL DEFAULT 0",
    "ALTER TABLE stock_entries ADD COLUMN origin TEXT NOT NULL DEFAULT 'purchase'",
    "ALTER TABLE stock_entries ADD COLUMN warranty_id TEXT",
)

TABLE_STATEMENTS = (
    """
    CREATE TABLE sale_return_sequences (
        store_id TEXT PRIMARY KEY,
        next_number INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        CHECK (next_number > 0)
    )
    """,
    """
    CREATE TABLE sale_return_allocations (
        id TEXT PRIMARY KEY,
        store_id TEXT NOT NULL,
        return_id TEXT NOT NULL,
        sale_payment_id TEXT,
        receivable_id TEXT,
        method TEXT NOT NULL,
        gross_amount REAL NOT NULL DEFAULT 0,
        pending_reduction REAL NOT NULL DEFAULT 0,
        refunded_amount REAL NOT NULL DEFAULT 0,
        status TEXT NOT NULL,
        cash_movement_id TEXT,
        reconciliation_required INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        FOREIGN KEY (return_id) REFERENCES sale_returns(id) ON DELETE CASCADE,
        CHECK (gross_amount >= 0),
        CHECK (pending_reduction >= 0),
        CHECK (refunded_amount >= 0),
        CHECK (status IN ('pending_reduced', 'refunded', 'mixed', 'manual_reconciliation'))
    )
    """,
    """
    CREATE TABLE sale_return_receivable_reductions (
        id TEXT PRIMARY KEY,
        store_id TEXT NOT NULL,
        return_id TEXT NOT NULL,
        sale_payment_id TEXT NOT NULL,
        receivable_id TEXT NOT NULL,
        amount REAL NOT NULL,
        open_amount_before REAL NOT NULL,
        open_amount_after REAL NOT NULL,
        status_before TEXT NOT NULL,
        status_after TEXT NOT NULL,
        created_at TEXT NOT NULL,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        FOREIGN KEY (return_id) REFERENCES sale_returns(id) ON DELETE CASCADE,
        FOREIGN KEY (receivable_id) REFERENCES receivables(id),
        CHECK (amount > 0),
        CHECK (open_amount_before >= 0),
        CHECK (open_amount_after >= 0)
    )
    """,
    """
    CREATE TABLE exchange_sequences (
        store_id TEXT PRIMARY KEY,
        next_number INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        CHECK (next_number > 0)
    )
    """,
    """
    CREATE TABLE exchanges (
        id TEXT PRIMARY KEY,
        store_id TEXT NOT NULL,
        exchange_number INTEGER NOT NULL,
        sale_id TEXT NOT NULL,
        customer_id TEXT,
        customer_name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'completed',
        origin TEXT NOT NULL DEFAULT 'commercial',
        warranty_id TEXT,
        reason TEXT NOT NULL,
        notes TEXT,
        credit_total REAL NOT NULL DEFAULT 0,
        new_items_total REAL NOT NULL DEFAULT 0,
        difference_amount REAL NOT NULL DEFAULT 0,
        difference_direction TEXT NOT NULL DEFAULT 'none',
        linked_sale_id TEXT,
        user_id TEXT,
        user_name TEXT,
        idempotency_key TEXT,
        request_hash TEXT,
        response_json TEXT,
        reconciliation_required INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        FOREIGN KEY (sale_id) REFERENCES sales(id),
        CHECK (exchange_number > 0),
        CHECK (status IN ('completed', 'cancelled')),
        CHECK (origin IN ('commercial', 'warranty')),
        CHECK (credit_total >= 0),
        CHECK (new_items_total >= 0),
        CHECK (difference_amount >= 0),
        CHECK (difference_direction IN ('pay', 'refund', 'none'))
    )
    """,
    """
    CREATE TABLE exchange_return_items (
        id TEXT PRIMARY KEY,
        exchange_id TEXT NOT NULL,
        sale_item_id TEXT NOT NULL,
        product_id TEXT NOT NULL,
        barcode TEXT,
        name TEXT NOT NULL,
        brand TEXT,
        size TEXT,
        color TEXT,
        quantity INTEGER NOT NULL,
        unit_credit REAL NOT NULL DEFAULT 0,
        credit_total REAL NOT NULL DEFAULT 0,
        unit_cost REAL NOT NULL DEFAULT 0,
        cost_total REAL NOT NULL DEFAULT 0,
        physical_condition TEXT NOT NULL,
        restocked INTEGER NOT NULL DEFAULT 0,
        FOREIGN KEY (exchange_id) REFERENCES exchanges(id) ON DELETE CASCADE,
        CHECK (quantity > 0),
        CHECK (unit_credit >= 0),
        CHECK (credit_total >= 0),
        CHECK (unit_cost >= 0),
        CHECK (cost_total >= 0),
        CHECK (physical_condition IN ('resellable', 'damaged'))
    )
    """,
    """
    CREATE TABLE exchange_new_items (
        id TEXT PRIMARY KEY,
        exchange_id TEXT NOT NULL,
        product_id TEXT NOT NULL,
        barcode TEXT,
        name TEXT NOT NULL,
        brand TEXT,
        size TEXT,
        color TEXT,
        quantity INTEGER NOT NULL,
        original_unit_price REAL NOT NULL DEFAULT 0,
        practiced_unit_price REAL NOT NULL DEFAULT 0,
        unit_discount REAL NOT NULL DEFAULT 0,
        unit_addition REAL NOT NULL DEFAULT 0,
        net_total REAL NOT NULL DEFAULT 0,
        unit_cost REAL NOT NULL DEFAULT 0,
        cost_total REAL NOT NULL DEFAULT 0,
        stock_before INTEGER NOT NULL,
        stock_after INTEGER NOT NULL,
        FOREIGN KEY (exchange_id) REFERENCES exchanges(id) ON DELETE CASCADE,
        CHECK (quantity > 0),
        CHECK (original_unit_price >= 0),
        CHECK (practiced_unit_price >= 0),
        CHECK (unit_discount >= 0),
        CHECK (unit_addition >= 0),
        CHECK (net_total >= 0),
        CHECK (unit_cost >= 0),
        CHECK (cost_total >= 0),
        CHECK (stock_before >= 0),
        CHECK (stock_after >= 0)
    )
    """,
    """
    CREATE TABLE exchange_payments (
        id TEXT PRIMARY KEY,
        exchange_id TEXT NOT NULL,
        method TEXT NOT NULL,
        amount REAL NOT NULL DEFAULT 0,
        direction TEXT NOT NULL,
        sale_payment_id TEXT,
        cash_movement_id TEXT,
        receivable_id TEXT,
        FOREIGN KEY (exchange_id) REFERENCES exchanges(id) ON DELETE CASCADE,
        CHECK (amount >= 0),
        CHECK (direction IN ('in', 'out'))
    )
    """,
    """
    CREATE TABLE exchange_cancellations (
        id TEXT PRIMARY KEY,
        store_id TEXT NOT NULL,
        exchange_id TEXT NOT NULL,
        reason TEXT NOT NULL,
        idempotency_key TEXT NOT NULL,
        request_hash TEXT NOT NULL,
        response_json TEXT NOT NULL,
        user_id TEXT,
        user_name TEXT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        FOREIGN KEY (exchange_id) REFERENCES exchanges(id),
        UNIQUE (exchange_id),
        CHECK (reason <> '')
    )
    """,
    """
    CREATE TABLE warranty_sequences (
        store_id TEXT PRIMARY KEY,
        next_number INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        CHECK (next_number > 0)
    )
    """,
    """
    CREATE TABLE warranties (
        id TEXT PRIMARY KEY,
        store_id TEXT NOT NULL,
        warranty_number INTEGER NOT NULL,
        sale_id TEXT NOT NULL,
        sale_item_id TEXT NOT NULL,
        customer_id TEXT,
        customer_name TEXT NOT NULL,
        contact_name TEXT,
        contact_phone TEXT,
        product_id TEXT NOT NULL,
        barcode TEXT,
        product_name TEXT NOT NULL,
        brand TEXT,
        size TEXT,
        color TEXT,
        quantity INTEGER NOT NULL,
        defect_category TEXT NOT NULL,
        defect_description TEXT NOT NULL,
        physical_location TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'open',
        supplier_id TEXT,
        supplier_name TEXT,
        supplier_protocol TEXT,
        solution_type TEXT,
        solution_reference_id TEXT,
        awaiting_customer_delivery INTEGER NOT NULL DEFAULT 0,
        opened_by_user_id TEXT,
        opened_by_user_name TEXT,
        idempotency_key TEXT,
        request_hash TEXT,
        response_json TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        resolved_at TEXT,
        cancelled_at TEXT,
        FOREIGN KEY (store_id) REFERENCES stores(id),
        FOREIGN KEY (sale_id) REFERENCES sales(id),
        CHECK (warranty_number > 0),
        CHECK (quantity > 0),
        CHECK (physical_location IN ('customer', 'store', 'supplier')),
        CHECK (status IN ('open', 'analysis', 'supplier', 'approved', 'rejected', 'resolved', 'cancelled'))
    )
    """,
    """
    CREATE TABLE warranty_photos (
        id TEXT PRIMARY KEY,
        warranty_id TEXT NOT NULL,
        url TEXT NOT NULL,
        storage TEXT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (warranty_id) REFERENCES warranties(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE warranty_events (
        id TEXT PRIMARY KEY,
        warranty_id TEXT NOT NULL,
        store_id TEXT NOT NULL,
        event_type TEXT NOT NULL,
        previous_status TEXT,
        new_status TEXT,
        notes TEXT,
        supplier_id TEXT,
        supplier_name TEXT,
        protocol TEXT,
        replacement_product_id TEXT,
        replacement_product_name TEXT,
        replacement_quantity INTEGER,
        replacement_unit_cost REAL,
        replacement_destination TEXT,
        stock_entry_id TEXT,
        user_id TEXT,
        user_name TEXT,
        created_at TEXT NOT NULL,
        FOREIGN KEY (warranty_id) REFERENCES warranties(id) ON DELETE CASCADE,
        FOREIGN KEY (store_id) REFERENCES stores(id)
    )
    """,
)

INDEX_STATEMENTS = (
    "CREATE UNIQUE INDEX idx_sale_returns_store_number ON sale_returns(store_id, return_number) WHERE return_number IS NOT NULL",
    "CREATE UNIQUE INDEX idx_sale_returns_store_idempotency ON sale_returns(store_id, idempotency_key) WHERE idempotency_key IS NOT NULL",
    "CREATE INDEX idx_sale_return_items_sale_item ON sale_return_items(sale_item_id)",
    "CREATE INDEX idx_sale_return_allocations_return ON sale_return_allocations(store_id, return_id)",
    "CREATE INDEX idx_sale_return_allocations_receivable ON sale_return_allocations(receivable_id)",
    "CREATE INDEX idx_sale_return_reductions_return ON sale_return_receivable_reductions(store_id, return_id)",
    "CREATE INDEX idx_sale_return_reductions_receivable ON sale_return_receivable_reductions(receivable_id)",
    "CREATE UNIQUE INDEX idx_exchanges_store_number ON exchanges(store_id, exchange_number)",
    "CREATE UNIQUE INDEX idx_exchanges_store_idempotency ON exchanges(store_id, idempotency_key) WHERE idempotency_key IS NOT NULL",
    "CREATE INDEX idx_exchanges_sale ON exchanges(store_id, sale_id, created_at)",
    "CREATE INDEX idx_exchange_return_items_sale_item ON exchange_return_items(sale_item_id)",
    "CREATE INDEX idx_exchange_new_items_product ON exchange_new_items(product_id)",
    "CREATE UNIQUE INDEX idx_exchange_cancellations_store_key ON exchange_cancellations(store_id, idempotency_key)",
    "CREATE UNIQUE INDEX idx_exchange_cancellations_exchange ON exchange_cancellations(exchange_id)",
    "CREATE UNIQUE INDEX idx_warranties_store_number ON warranties(store_id, warranty_number)",
    "CREATE UNIQUE INDEX idx_warranties_store_idempotency ON warranties(store_id, idempotency_key) WHERE idempotency_key IS NOT NULL",
    "CREATE INDEX idx_warranties_sale ON warranties(store_id, sale_id, created_at)",
    "CREATE INDEX idx_warranties_customer_status ON warranties(store_id, customer_id, status)",
    "CREATE INDEX idx_warranties_supplier_status ON warranties(store_id, supplier_id, status)",
    "CREATE INDEX idx_warranties_product_status ON warranties(store_id, product_id, status)",
    "CREATE INDEX idx_warranty_events_warranty ON warranty_events(warranty_id, created_at)",
    "CREATE INDEX idx_warranty_photos_warranty ON warranty_photos(warranty_id)",
    "CREATE INDEX idx_sales_exchange ON sales(exchange_id)",
    "CREATE INDEX idx_sales_warranty ON sales(warranty_id)",
)


MIGRATION_013 = Migration(
    version=13,
    description="Add transactional returns, exchanges and warranties",
    sqlite_statements=(*ALTER_STATEMENTS, *TABLE_STATEMENTS, *INDEX_STATEMENTS),
    postgresql_statements=(*ALTER_STATEMENTS, *TABLE_STATEMENTS, *INDEX_STATEMENTS),
    code_id="mova-sports-returns-exchanges-warranties-v13",
)
